version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "10:00"
    timezone: Etc/UCT
  reviewers:
  - fkolar
  - InnaAtanasova
  - KevinOkamoto
  - mikerodonnell89
  - droshev
  open-pull-requests-limit: 10
