apiVersion: v1alpha
kind: cypress
defaults: {}
showconsolelog: false
sauce:
  region: eu-central-1
  concurrency: 337
  sauceignore: .sauceignore
cypress:
  configFile: cypress.json
  version: 7.7.0
  record: false
  key: ""
suites:
- name: cypress - windows 10 - chrome
  browser: chrome
  platformName: windows 10
  config:
    testFiles:
    - '**/*.*'
  mode: sauce
rootDir: .
artifacts:
  download:
    match:
    - '*'
    when: never
    directory: ./artifacts
