apiVersion: v1alpha
kind: cypress
defaults: {
  mode: sauce
}
showconsolelog: false
sauce:
  region: eu-central-1
  concurrency: 30
  sauceignore: .sauceignore
  tunnel:
#    sauce tunnel ID (Tunnel Name)
    id: sso-sap-C5315352_tunnel_id
cypress:
  configFile: cypress.json
  version: 7.7.0
  record: false
  key: ""
suites:
- name: "cypress test"
  browser: "chrome"
  platformName: "Windows 10"
  screenResolution: "1920x1080"
  config:
    testFiles: ["**/*.e2e-spec.ts"]
  mode: sauce
rootDir: .
artifacts:
  download:
    match:
    - '*'
    when: never
    directory: ./artifacts
npm:
  registry: https://registry.npmjs.org
  packages:
    "typescript": "4.1.6"
